### ISSUE TITLE
Please check the issue.

### ISSUE THREAD

**Issue by progss57** [binary-husky/hmp2g#11]
1. After all the procedures, render_result.jsonc was executed.
![image](https://github.com/user-attachments/assets/e63b9334-5631-4260-8f59-7b661fa36254)

(hmp_env) PS C:\Users\user\Documents\GitHub\hmp2g_01> python main.py -c RESULT/uhmap_hete10vs10/render_result.jsonc

2. There's a problem
![image](https://github.com/user-attachments/assets/5cc443a6-910b-458e-8e53-413c440b3187)

Port 55578 will be used by hmp, port 55579 will be used by UE internally
checking ScenarioConfig args problems ...
downloading Uhmap_Windows_Build_Version3.5
download uhmap file manifest | 下载manifest目录文件
  0%|                                                                                      | 0.00/274k [00:00<?, ?iB/s][Errno 13] Permission denied: './TEMP/EVmCQMSUWV5MgREWaxiz_GoBalBRV3DWBU3ToSJ5OTQaLQ'
failed to connect to onedrive | 连接onedrive失败, 您可能需要翻墙才能下载资源
  0%|                                                                                      | 0.00/274k [00:00<?, ?iB/s]
Process SuperProc-1:
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\hmp_env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\user\Documents\GitHub\hmp2g_01\UTIL\win_pool.py", line 83, in run
    self.add_targets(self.pH.recv())
  File "C:\Users\user\Documents\GitHub\hmp2g_01\UTIL\win_pool.py", line 54, in add_targets
    self.automatic_generation(name, gen_fn, *arg)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\UTIL\win_pool.py", line 43, in automatic_generation
    setattr(self, name, gen_fn(*arg))
  File "C:\Users\user\Documents\GitHub\hmp2g_01\UTIL\shm_env.py", line 24, in __init__
    self._env = env_init_fn()
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\env_router.py", line 64, in <lambda>
    return lambda: env_init_function(env_name, rank)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\uhmap\uhmap_env_wrapper.py", line 19, in make_uhmap_env
    return ST_CLASS(rank)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\uhmap\SubTasks\UhmapLargeScale.py", line 18, in __init__
    super().__init__(rank)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\uhmap\uhmap_env_wrapper.py", line 171, in __init__
    self.activate_simulation(self.id, find_port=True)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\uhmap\uhmap_env_wrapper.py", line 239, in activate_simulation
    download_client_binary(desired_path=simulation_exe, desired_version=ScenarioConfig.UhmapVersion, is_render_client=self.render)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\uhmap\auto_download.py", line 45, in download_client_binary
    download_client_binary_on_platform(desired_path, desired_version, is_render_client, platform=plat)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\uhmap\auto_download.py", line 32, in download_client_binary_on_platform
    download_from_shared_server(key = key)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\uhmap\auto_download.py", line 17, in download_from_shared_server
    with open("./TEMP/uhmap_manifest.jsonc", "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: './TEMP/uhmap_manifest.jsonc'
 [shm_env.py] Gym Space is unable to transfer between processes, using string instead
Traceback (most recent call last):
  File "C:\Users\user\anaconda3\envs\hmp_env\lib\multiprocessing\connection.py", line 312, in _recv_bytes
    nread, err = ov.GetOverlappedResult(True)
BrokenPipeError: [WinError 109] 파이프가 끝났습니다

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\hmp2g_01\UTIL\shm_env.py", line 134, in __init__
    self.observation_space = self.SuperPool.exec_target(name=self.env, dowhat='get_obs_space')[0]
  File "C:\Users\user\Documents\GitHub\hmp2g_01\UTIL\win_pool.py", line 152, in exec_target
    res_sort.extend(self.thisSide[j].recv())
  File "C:\Users\user\anaconda3\envs\hmp_env\lib\multiprocessing\connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "C:\Users\user\anaconda3\envs\hmp_env\lib\multiprocessing\connection.py", line 321, in _recv_bytes
    raise EOFError
EOFError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 86, in <module>
    runner = Runner(process_pool=smart_pool)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\task_runner.py", line 19, in __init__
    self.envs = make_parallel_envs(process_pool)          # parallel environments start
  File "C:\Users\user\Documents\GitHub\hmp2g_01\MISSION\env_router.py", line 115, in make_parallel_envs
    envs = SuperpoolEnv(process_pool, env_args_dict_list)
  File "C:\Users\user\Documents\GitHub\hmp2g_01\UTIL\shm_env.py", line 138, in __init__
    self.observation_space = self.SuperPool.exec_target(name=self.env, dowhat='get_obs_space_str')[0]
  File "C:\Users\user\Documents\GitHub\hmp2g_01\UTIL\win_pool.py", line 149, in exec_target
    self.thisSide[j].send(tuple_list_to_be_send)
  File "C:\Users\user\anaconda3\envs\hmp_env\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\user\anaconda3\envs\hmp_env\lib\multiprocessing\connection.py", line 280, in _send_bytes
    ov, err = _winapi.WriteFile(self._handle, buf, overlapped=True)
BrokenPipeError: [WinError 232] 파이프가 닫히는 중입니다
[win_pool]: executing superpool del
[win_pool]: Sending exit command to workers ...
[win_pool]: Closing pipe ...
 [win_pool]: terminate in 2, please wait for a clean up
 [win_pool]: terminate in 1, please wait for a clean up
 [shm_pool]: __del__ finish

**Comment by kafuuCocoa** [comment]
Have you tried changing "UElink2editor": false to true in “render_result”?

**Comment by progss57** [comment]
![image](https://github.com/user-attachments/assets/a868f9e0-8ca7-4f2a-b025-b8855e12d599)
It works well. When I set like this:
"render": false,
"UElink2editor": true,

But did not work, when set like this:
"render": true,
"UElink2editor": false,
![image](https://github.com/user-attachments/assets/be0f5cb8-65f1-48e0-90f3-bcce07db89d3)
![image](https://github.com/user-attachments/assets/5783b980-158d-4ba2-8d15-415007d2638d)

**Comment by kafuuCocoa** [comment]
When running Please_Run_This_First_To_Fetch_Big_Files.py in UMAP, a similar error also occurs. The owner addressed these related questions about 'from onedrive to modelscope' and updated the code in https://github.com/binary-husky/unreal-map/pull/12, but the changes have not been applied to this project.
