### ISSUE TITLE
error running on windows

### ISSUE THREAD

**Issue by LeeSword12** [binary-husky/hmp2g#4]
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2019.3.5\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "./THIRDPARTY/pymarl2/pymarl2src/main.py", line 126, in <module>
    my_main(None, config_dict, None)
  File "./THIRDPARTY/pymarl2/pymarl2src/main.py", line 52, in my_main
    run_REGISTRY[_config['run']](_run, config, _log)
  File "D:\2023Work\1IntelligentBattle\hmp2g-master\THIRDPARTY\pymarl2\pymarl2src\run\run.py", line 52, in run
    run_sequential(args=args, logger=logger)
  File "D:\2023Work\1IntelligentBattle\hmp2g-master\THIRDPARTY\pymarl2\pymarl2src\run\run.py", line 85, in run_sequential
    runner = r_REGISTRY[args.runner](args=args, logger=logger)
  File "D:\2023Work\1IntelligentBattle\hmp2g-master\THIRDPARTY\pymarl2\pymarl2src\runners\efficient_parallel_runner.py", line 82, in __init__
    self.remote_link_client = UnixTcpClientP2P(unix_path, obj='pickle')
  File "D:\2023Work\1IntelligentBattle\hmp2g-master\UTIL\network.py", line 413, in __init__
    self.self_unix_path = target_unix_path+'_client_'+uuid.uuid1().hex[:5]
TypeError: can only concatenate tuple (not "str") to tuple

target_unix_path = ('localhost', 12235)

**Comment by binary-husky** [comment]
a compatibility bug in Windows 

can be fixed by changing "UnixTcpClientP2P"->"TcpClientP2P"   in "THIRDPARTY/pymarl2/pymarl2src/runners/efficient_parallel_runner.py"
![image](https://user-images.githubusercontent.com/96192199/216948140-5245726b-6a56-455c-9bf1-870736dc97c0.png)

later we'll find a Windows environment to test it.
